"""users table

Revision ID: 77e57ed79e4a
Revises: d743567d6c0b
Create Date: 2020-03-10 22:32:41.513441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e57ed79e4a'
down_revision = 'd743567d6c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('drive_file_id', sa.String(length=512), nullable=True))
    op.add_column('file', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('file', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=True)
    op.create_index(op.f('ix_file_timestamp'), 'file', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'file', 'user', ['owner'], ['id'])
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('drive_folder_id', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_foreign_key(None, 'user', 'role', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'role')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'drive_folder_id')
    op.drop_column('user', 'about_me')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_index(op.f('ix_file_timestamp'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_column('file', 'timestamp')
    op.drop_column('file', 'owner')
    op.drop_column('file', 'name')
    op.drop_column('file', 'drive_file_id')
    # ### end Alembic commands ###
