"""empty message

Revision ID: a61f851b4d54
Revises: 8666d66dc357
Create Date: 2020-03-11 13:42:15.777061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61f851b4d54'
down_revision = '8666d66dc357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_timestamp'), 'new', ['timestamp'], unique=False)
    op.create_table('block_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('block_message', sa.Boolean(), nullable=True),
    sa.Column('block_article', sa.Boolean(), nullable=True),
    sa.Column('block_file', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compilation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('file', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compilation_timestamp'), 'compilation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compilation_timestamp'), table_name='compilation')
    op.drop_table('compilation')
    op.drop_table('block_user')
    op.drop_index(op.f('ix_new_timestamp'), table_name='new')
    op.drop_table('new')
    # ### end Alembic commands ###
