"""empty message

Revision ID: b267386670a7
Revises: a61f851b4d54
Create Date: 2020-05-28 22:44:05.285805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b267386670a7'
down_revision = 'a61f851b4d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_name', table_name='file')
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.create_index('ix_file_name', 'file', ['name'], unique=1)
    # ### end Alembic commands ###
